## Exercise 6 - Numpy

1 Generate two NumPy arrays so that first array has integers from 10 to 40 (inclusive). Second array should have 30 integers from 220 to 250 (inclusive). Sum these arrays and present the result array.

In [5]:
import numpy as np

arr1 = np.arange(10, 41)

arr2 = np.arange(220, 251)

res_arr = arr1 + arr2

res_arr

array([230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254,
       256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280,
       282, 284, 286, 288, 290])

2 Generate two-dimensional array with 10 rows and 7 columns containing integers starting from 100.

In [10]:
dim_arr = np.arange(100, 170).reshape(10,7)

dim_arr

array([[100, 101, 102, 103, 104, 105, 106],
       [107, 108, 109, 110, 111, 112, 113],
       [114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127],
       [128, 129, 130, 131, 132, 133, 134],
       [135, 136, 137, 138, 139, 140, 141],
       [142, 143, 144, 145, 146, 147, 148],
       [149, 150, 151, 152, 153, 154, 155],
       [156, 157, 158, 159, 160, 161, 162],
       [163, 164, 165, 166, 167, 168, 169]])

3 Generate three-dimensional array (3x3x3) with random floats.

In [13]:
three_dim_arr = np.random.rand(3,3,3)

three_dim_arr

array([[[0.1349328 , 0.93350386, 0.05341497],
        [0.37033862, 0.57602609, 0.97677028],
        [0.57470939, 0.3200262 , 0.21977443]],

       [[0.10733179, 0.77293757, 0.98512835],
        [0.02188072, 0.37621734, 0.75650246],
        [0.37847445, 0.89089523, 0.04859467]],

       [[0.03126056, 0.38234211, 0.86587259],
        [0.7350474 , 0.43453397, 0.27809247],
        [0.76698491, 0.33137933, 0.5490874 ]]])

4 Generate two one-dimensional arrays having integers between 1-50. First array should have even and second array should have odd numbers. Finally multiply each corresponding numbers from these two arrays for the result array.

In [23]:
first_arr = np.arange(2,51,2)

second_arr = np.arange(1,51,2)

result_arr = first_arr * second_arr

result_arr

array([   2,   12,   30,   56,   90,  132,  182,  240,  306,  380,  462,
        552,  650,  756,  870,  992, 1122, 1260, 1406, 1560, 1722, 1892,
       2070, 2256, 2450])

5 Generate two-dimensional array (40 rows, 5 columns) containing random integers between 1 and 1000. Filter the result array so that only numbers divisable with numbers 2 and 6 are presented.

In [46]:
randint_arr = np.random.randint(1,1000, size=(40,5))



query = np.where((randint_arr % 6 == 0) & (randint_arr % 2 == 0))

result = randint_arr[query]

result

array([552, 228, 456,  54, 528, 534,  96, 738, 372, 732, 804, 624, 396,
       546, 852, 564, 474, 462, 372, 318, 834, 630, 888, 540, 222, 282,
        30, 564, 912, 606, 426,  72, 324, 636, 876, 366, 834, 216, 864,
       270,  78, 366, 468, 498])